### PR TITLE
ADAPT-8593

### PR DESCRIPTION
**Pull request by ethan-lp**
removed incorrect css class -face and changed preventDefault to stopProp for <a> tag to work

### CODE REVIEW

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by eleanor-heath** [comment]
@christopher-learningpool I tested whether the github release action gets triggered automatically in this PR https://github.com/HT2-Labs/adapt-contrib-flipcard/pull/68 after your workflow updates were merged in, it didnt seem to be triggered.

**Comment by eleanor-heath** [comment]
@christopher-learningpool nevermind - it was triggered a minute ago 😅

**Comment by cahirodoherty-learningpool** [comment]
Closing as outdated

**Pull request closed without merging**
