### PR TITLE
ADAPT-8235 - Flipcard Accessibility Issues

### PR DESCRIPTION
**Pull request by eleanor-heath**
Add focus to flipcard on the front and back and made sure that the filpcard front/back face maintains focus every time you click on the flipcard.  Also made each side a button so that the screen reader would recognise it as a clickable element. Updated functions to arrow functions

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by ethan-lp — APPROVED** [review]
👀

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by ethan-lp — APPROVED** [review]
👀

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
